apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deepframe
nameSuffix: -dev

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: patch-http-route.yaml
labels:
  - includeSelectors: false
    pairs:
      environment: dev

# Secret management:
# kubectl create secret generic open-webui-dev-secret \
#   --namespace deepframe \
#   --from-literal=WEBUI_SECRET_KEY="$(openssl rand -hex 32)"
